from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    Table, TableStyle, KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from models import MatchResult

# ── Color palette ─────────────────────────────────────────────────────────────
DARK       = colors.HexColor("#0F172A")
ACCENT     = colors.HexColor("#6366F1")   # indigo
SUCCESS    = colors.HexColor("#10B981")   # emerald
WARNING    = colors.HexColor("#F59E0B")   # amber
DANGER     = colors.HexColor("#EF4444")   # red
LIGHT_BG   = colors.HexColor("#F8FAFC")
MUTED      = colors.HexColor("#64748B")
WHITE      = colors.white


def _score_color(score: int):
    if score >= 75:
        return SUCCESS
    elif score >= 50:
        return WARNING
    return DANGER


def _flag_color(flag: str):
    return {
        "good": SUCCESS,
        "vague": WARNING,
        "weak": WARNING,
        "hallucinated": DANGER,
    }.get(flag, MUTED)


def generate_pdf_report(result: MatchResult) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    base = getSampleStyleSheet()
    story = []

    # Custom styles 
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=base["Normal"],
        fontSize=22,
        fontName="Helvetica-Bold",
        textColor=DARK,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=base["Normal"],
        fontSize=11,
        fontName="Helvetica",
        textColor=MUTED,
        spaceAfter=16,
    )
    h2_style = ParagraphStyle(
        "H2",
        parent=base["Normal"],
        fontSize=13,
        fontName="Helvetica-Bold",
        textColor=DARK,
        spaceBefore=18,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=base["Normal"],
        fontSize=10,
        fontName="Helvetica",
        textColor=DARK,
        spaceAfter=4,
        leading=15,
    )
    muted_style = ParagraphStyle(
        "Muted",
        parent=body_style,
        textColor=MUTED,
        fontSize=9,
    )
    tag_style = ParagraphStyle(
        "Tag",
        parent=base["Normal"],
        fontSize=9,
        fontName="Helvetica",
        textColor=DARK,
    )

    def divider():
        return HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=8, spaceBefore=4)

    def pill_table(items, bg_color):
        """Render a list of items as colored pills in a table row."""
        if not items:
            return Paragraph("None identified.", muted_style)
        cells = [[Paragraph(item, tag_style) for item in items]]
        t = Table(cells, hAlign="LEFT")
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg_color),
            ("TEXTCOLOR", (0, 0), (-1, -1), WHITE),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROUNDEDCORNERS", [4, 4, 4, 4]),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [bg_color]),
        ]))
        return t

    # Header 
    story.append(Paragraph("AI Resume + Job Match Report", title_style))
    story.append(Paragraph("Generated by AI Resume + Job Match Agent", subtitle_style))
    story.append(divider())

    # Score summary row 
    llm_score = result.match_score.score
    sem_pct = result.semantic_similarity.percentage if result.semantic_similarity else "N/A"

    score_data = [
        [
            Paragraph("LLM Match Score", muted_style),
            Paragraph("Semantic Similarity", muted_style),
            Paragraph("Eval Quality", muted_style),
        ],
        [
            Paragraph(f"<font size=28><b>{llm_score}</b></font><font size=11> / 100</font>", ParagraphStyle("sc", parent=base["Normal"], textColor=_score_color(llm_score))),
            Paragraph(f"<font size=28><b>{sem_pct}</b></font><font size=11> / 100</font>", ParagraphStyle("sc2", parent=base["Normal"], textColor=_score_color(sem_pct if isinstance(sem_pct, int) else 50))),
            Paragraph(f"<font size=28><b>{result.eval_report.overall_quality if result.eval_report else 'N/A'}</b></font><font size=11> / 10</font>", ParagraphStyle("sc3", parent=base["Normal"], textColor=ACCENT)),
        ],
    ]

    score_table = Table(score_data, colWidths=[2.2 * inch, 2.2 * inch, 2.2 * inch])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#E2E8F0")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 12))

    # LLM Match Score 
    story.append(Paragraph("Match Analysis", h2_style))
    story.append(Paragraph(result.match_score.reasoning, body_style))

    story.append(Spacer(1, 6))
    story.append(Paragraph("<b>Strong matches</b>", body_style))
    story.append(pill_table(result.match_score.strong_matches, SUCCESS))
    story.append(Spacer(1, 8))
    story.append(Paragraph("<b>Partial matches</b>", body_style))
    story.append(pill_table(result.match_score.weak_matches, WARNING))

    # Semantic Similarity 
    if result.semantic_similarity:
        story.append(Paragraph("Semantic Similarity", h2_style))
        story.append(divider())
        story.append(Paragraph(result.semantic_similarity.interpretation, body_style))
        story.append(Paragraph(
            f"Cosine similarity score: <b>{result.semantic_similarity.score}</b> — "
            "this is a mathematical embedding comparison, independent of the LLM's analysis.",
            muted_style,
        ))

    # Gap Analysis 
    story.append(Paragraph("Gap Analysis", h2_style))
    story.append(divider())

    sections = [
        ("Missing Skills", result.gap_analysis.missing_skills, DANGER),
        ("Missing Experience", result.gap_analysis.missing_experience, WARNING),
        ("Missing ATS Keywords", result.gap_analysis.missing_keywords, colors.HexColor("#8B5CF6")),
        ("Priority Gaps (fix these first)", result.gap_analysis.priority_gaps, DARK),
    ]
    for label, items, color in sections:
        story.append(Paragraph(f"<b>{label}</b>", body_style))
        story.append(pill_table(items, color))
        story.append(Spacer(1, 8))

    # Resume Suggestions
    story.append(Paragraph("Resume Improvement Suggestions", h2_style))
    story.append(divider())
    story.append(Paragraph(result.resume_suggestions.summary_advice, body_style))
    story.append(Spacer(1, 8))

    eval_map = {}
    if result.eval_report:
        eval_map = {e.suggestion_index: e for e in result.eval_report.evaluations}

    for i, s in enumerate(result.resume_suggestions.suggestions):
        ev = eval_map.get(i)
        flag = ev.flag if ev else "—"
        flag_color = _flag_color(flag) if ev else MUTED
        quality = f"  Quality: {ev.quality_score}/10" if ev else ""

        header = [
            Paragraph(f"<b>{s.section}</b>", body_style),
            Paragraph(f"<font color='#{flag_color.hexval()[1:]}'>● {flag.upper()}</font>{quality}", muted_style),
        ]
        header_table = Table([header], colWidths=[3.5 * inch, 3 * inch])
        header_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))

        rows = [
            [header_table],
            [Paragraph(f"<i>Before:</i> {s.original}", muted_style)] if s.original else [],
            [Paragraph(f"<b>Suggestion:</b> {s.suggestion}", body_style)],
            [Paragraph(f"<i>Why:</i> {s.reason}", muted_style)],
        ]
        rows = [r for r in rows if r]

        card = Table(rows, colWidths=[6.5 * inch])
        card.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LINEAFTER", (0, 0), (0, -1), 3, flag_color),
        ]))
        story.append(KeepTogether([card, Spacer(1, 8)]))

    # Eval Summary 
    if result.eval_report:
        story.append(Paragraph("Self-Eval Summary", h2_style))
        story.append(divider())
        story.append(Paragraph(result.eval_report.eval_summary, body_style))

    doc.build(story)
    return buffer.getvalue()